[package]
name = "xj_cstr"
version = "0.1.3"
edition = "2024"
description = "Safe implementations of core C string APIs"
license = "MIT"
repository = "https://github.com/brk/xj_cstr"

[dependencies]
bytemuck = "1.25.0"
